# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
 languageCode: zh-Hans
 contentDir: content/zh
 title: Tianyu Zhang(张天雨)
 params:
   description: Site description in Chinese...

# baseURL: 'https://tianyuzhang07.github.io/TianyuZhang.github.io/zh/'
 menu:
   main:
     - name: 主页
       url: '/zh/'
       weight: 1
     - name: 研究方向
       url: '/zh/#papers'
       weight: 2
     - name: 研究成果
       url: '/zh/#publications'
       weight: 3
     - name: 科研项目
       url: '/zh/#projects'
       weight: 4
     - name: 工作经历
       url: '/zh/#experience'
       weight: 5